version: 1
websocket: 
  host: '127.0.0.1'
  port: 5800
  uri: '/api/'
rabbitmq:
  host: '127.0.0.1'
  port: 5672
  exchange: 'messageRecv'
  exchange_type: 'direct'
  user: 'user'
  password: '123456'
  virtualhost: '/'
  queue: 'messageRecvQueue'
  prefetch_count: 1