version: 1
websocket:
  host: "127.0.0.1"
  port: 5800
  uri: "/api/"
sendRabbitmq:
  host: "127.0.0.1"
  port: 5672
  exchange: "messageSend"
  exchange_type: "direct"
  user: "user"
  password: "123456"
  virtualhost: "/"
  queue: "messageSendQueue"
  prefetch_count: 1
